# Generated by Django 3.1.2 on 2020-10-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
