# Generated by Django 3.1.2 on 2020-10-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201015_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
