# Generated by Django 3.1.2 on 2020-10-16 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20201016_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
