# Generated by Django 3.1.2 on 2020-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20201017_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(blank=True),
        ),
    ]
