# Generated by Django 3.1.2 on 2020-10-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20201018_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Highlight_Fur_Color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
